# Generated by Django 5.2.7 on 2025-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_petition_category_alter_petition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('legal', 'Legal Rights'), ('welfare', 'Public Welfare'), ('environment', 'Environmental'), ('policy', 'Policy Reform')], default='general', max_length=100),
        ),
    ]
